### ISSUE TITLE
Missing call to setgroups before setuid

### ISSUE THREAD

**Issue by msimacek** [eclipse/jetty.toolchain#6] opened 2016-09-26 15:13 UTC
Calling setuid changes the UIDs to regular user, but keeps supplementary groups, so a potential attacker can still gain access to those. It should call `setgroups(0, NULL)` before calling setuid.

**Comment by mattsheppard** [comment] 2020-02-24 05:15
I just bumped into this as well.

I'd be happy to try to build a PR for it, but I can't currently actually see how the setuid stuff is built. If anyone can point me in the right direction I'd appreciate it!

**Comment by gregw** [comment] 2020-02-24 07:59
@mattsheppard you need to give us a PR against https://github.com/eclipse/jetty.toolchain/tree/master/jetty-setuid, which is released much less frequently

**Comment by mattsheppard** [comment] 2020-02-24 08:48
Yeah, I think I found my way there, but then found maven is currently unable to build it with the error below.

Happy to try to sort that out too if that's what needs to happen, I was just assuming I was doing something wrong.

```
jetty.toolchain> mvn -P setuid clean package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.eclipse.jetty.toolchain.setuid:jetty-setuid-parent:1.0.3-SNAPSHOT: Could not find artifact org.eclipse.jetty.toolchain:jetty-toolchain:pom:1.6-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 2, column 13
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-remote-resources-plugin is missing. @ line 73, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-remote-resources-plugin is missing. @ line 66, column 15
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.eclipse.jetty.toolchain.setuid:jetty-setuid-parent:1.0.3-SNAPSHOT (/Users/matt/Documents/Funnelback/jetty.toolchain/jetty-setuid/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.jetty.toolchain.setuid:jetty-setuid-parent:1.0.3-SNAPSHOT: Could not find artifact org.eclipse.jetty.toolchain:jetty-toolchain:pom:1.6-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 2, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by olamy** [comment] 2020-02-24 09:03
change the parent to version 1.7

**Comment by mattsheppard** [comment] 2020-02-26 22:26
Would you consider making the _clearSupplementalGroups boolean in https://github.com/eclipse/jetty.toolchain/commit/59a9586c37768df2bbb1de35cfacf11c76c27ceddefault to true?

I appreciate it would be a change in the previous behaviour that might sometimes be undesirable, however the existing behaviour seems risky.

My specific experience was that I had set the uid and gid as I thought I was intended with the setuid support, and then only later discovered Jetty was still running with root privileges because of a supplemental group. Obviously I'll know to set this new boolean correctly going forward, but I worry that other people who set the uid and gid in the past and thought they were done will remain affected because they'll never become aware of the new setting.

**Comment by jmcc0nn3ll** [comment] 2020-02-26 22:42
Staged here: 
https://oss.sonatype.org/content/repositories/jetty-1525

**Comment by gregw** [comment] 2020-02-26 22:49
@mattsheppard we can set the default in the jetty distro (see https://github.com/eclipse/jetty.project/pull/4609).  Currently I have that as false, to preserve behaviour, but I will change it to true when we merge forward to jetty-10.

**Comment by mattsheppard** [comment] 2020-02-27 00:29
Ok, makes sense.

Thanks for your help getting this one sorted!

**Comment by jmcc0nn3ll** [comment] 2020-02-27 13:20
@mattsheppard can you double check the staged artifacts work for you? If so we might be able to sneak into next release if we get lucky.

**Comment by mattsheppard** [comment] 2020-02-27 22:11
I'd be happy to, but I'm not sure where to get them from - https://oss.sonatype.org/content/repositories/jetty-1525 seems to give me a 404.

**Comment by jmcc0nn3ll** [comment] 2020-02-27 23:01
It was staged but we tested and released it, it is now in a staged release of Jetty proper. Would be great if you could test there!

https://oss.sonatype.org/content/repositories/jetty-1528

**Comment by mattsheppard** [comment] 2020-02-27 23:41
I feel like I must be missing something obvious, but I can't see where the setuid stuff resides in there at all - I was expecting to see jetty-setuid (or something toolchain related) under https://oss.sonatype.org/content/repositories/jetty-1528/org/eclipse/jetty/

**Comment by olamy** [comment] 2020-02-27 23:46
@mattsheppard it's in central maven now see https://repo.maven.apache.org/maven2/org/eclipse/jetty/toolchain/setuid/  and the new version is included in the staged distribution here: https://oss.sonatype.org/content/repositories/jetty-1528/org/eclipse/jetty/jetty-distribution/9.4.27.v20200227/

**Comment by mattsheppard** [comment] 2020-02-27 23:48
Ah, right, gotcha - I'll check it out.

**Comment by mattsheppard** [comment] 2020-02-28 00:14
Yep, seems to be working now in the case I had were supplemental groups were previously not being cleared. 🥂

**Comment by jmcc0nn3ll** [comment] 2020-02-28 02:40
good deal, closing this out then, thanks for the sanity check!

**Closed by jmcc0nn3ll** 2020-02-28 02:40 UTC
Labels: Bug
